project_id = "bqeohnojnqqewtcyzntz"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.elevenlabs-sfx]
    verify_jwt = false
  [functions.elevenlabs-transcribe]
    verify_jwt = false
  [functions.generate-ambient-sounds]
    verify_jwt = false
  [functions.note-ai]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = false
  [functions.run-code]
    verify_jwt = false
